### ISSUE TITLE
Lazymc Fails to Recognize Fabric Server Start (Force Killing Despite RCON and Sufficient Timeout)

### ISSUE THREAD

**Issue by Oli-70** [timvisee/lazymc#89]
### Description

I'm experiencing an issue where lazymc (version 0.2.11) triggers the start of my Fabric 1.20.1 server but fails to recognize when it has fully started, resulting in it not forwarding the port (`25565` to `25566`) and eventually force-killing the process despite sufficient `start_timeout` and RCON enabled. This occurs when managed through Crafty Controller. The client gets stuck at "Server is starting..." (both locally and via Playit.gg), and no further logs appear in lazymc after the initial proxy setup.

#### Steps to Reproduce
1. Set up a Fabric 1.20.1 server with `fabric-server-launcher.jar` and multiple mods (e.g., `spellbladenext`, `puffish_skills`), managed via Crafty Controller.
2. Configure lazymc with the following `lazymc.toml`:
   ```toml
   [public]
   address = "0.0.0.0:25565"
   version = "1.20.1"
   protocol = 763

   [server]
   address = "127.0.0.1:25566"
   command = "bash start.sh"
   start_timeout = 180
   stop_timeout = 900

   [join]
   methods = ["kick"]

   [join.kick]
   starting = "Server is starting... Please reconnect in 60 seconds."

   [rcon]
   enabled = true
   port = 25575
   password = "<masked>"
   ```
3. Configure `server.properties`:
   ```properties
   server-ip=0.0.0.0
   server-port=25566
   enable-rcon=true
   rcon.port=25575
   rcon.password=<masked>
   ```
4. Start lazymc via Crafty: Crafty executes a script that runs `./lazymc start` from the server directory.
5. Join locally (`localhost:25565`) or via Playit.gg (mapped to `127.0.0.1:25565`).

#### Expected Behavior
- Lazymc detects the join, starts the server, kicks the client with "Server is starting... Please reconnect in 60 seconds," recognizes the server as started (~65 seconds), and forwards the connection from `25565` to `25566`.
- Client can join after reconnecting.

#### Actual Behavior
- Client remains stuck at "Server is starting..." (both locally and via Playit.gg).
- Lazymc logs initially show:
  ```
  INFO  lazymc > Proxying public 0.0.0.0:25565 to server 127.0.0.1:25566
  ERROR lazymc > Client tried to switch into unknown protocol state (22), disconnecting
  ```
- No further logs appear when joining (neither "Starting server..." nor errors), though the server starts (visible in server logs).
- After ~1-2 minutes, lazymc logs:
  ```
  ERROR lazymc::monitor > Force killing server, took too long to start or stop
  WARN  lazymc          > Server process stopped with error code (signal: 9 (SIGKILL))
  ERROR lazymc::monitor > Force killing server, took too long to start or stop
  WARN  lazymc          > Failed to force kill server
  INFO  lazymc::monitor > Server is now sleeping
  ```
- Server starts fine without lazymc (via Crafty with direct `bash start.sh`, joinable on `localhost:25565` when I change the port to `25565` in `server.properties`).

#### Additional Details
- **Environment**: Ubuntu (TrueNAS-hosted), Fabric 1.20.1, lazymc 0.2.11, Crafty Controller, Playit.gg for tunneling (listening on `127.0.0.1:25565`).
- **Observations**:
  - Server starts fine without lazymc when port is set to `25565` (joinable on `localhost:25565`).
  - Same issue occurs locally (`localhost:25565`) and via Playit.gg, ruling out Playit as the cause.
  - Setting `forge = true` in `lazymc.toml` had no effect.
  - Lazymc triggers the server start, but doesn’t recognize completion or forward the port, leading to no new logs after joining beyond initial proxy setup.
- **Suspected Cause**: Lazymc misinterprets Fabric’s start completion (possibly due to protocol/RCON issues) and fails to forward the port when managed through Crafty, potentially a Fabric compatibility issue.
